.PHONY: help \
	reference-implementation-setup-install-dependencies \
	reference-implementation-setup-nitro-prepare \
	reference-implementation-setup-db-generate \
	reference-implementation-setup \
	reference-implementation-run-for-postman \
	reference-implementation-test-with-postman-and-already-launched-server \
	reference-implementation-test-with-postman \
	running-processes-clean \
	non-default-files-clean \
	documentation-setup \
	documentation-dev \
	documentation-dev-host \
	documentation-build \
	documentation-preview \
	documentation-clean

help:
	@echo "Reference Implementation:"
	@echo "  reference-implementation-setup"
	@echo "  reference-implementation-run-for-postman"
	@echo "  reference-implementation-test-with-postman"
	@echo "  running-processes-clean"
	@echo "  non-default-files-clean"
	@echo ""
	@echo "Documentation:"
	@echo "  documentation-setup"
	@echo "  documentation-dev"
	@echo "  documentation-dev-host"
	@echo "  documentation-build"
	@echo "  documentation-preview"
	@echo "  documentation-clean"

########################
# Reference Implementation - Setup

reference-implementation-setup-install-dependencies:
	cd apps/api && npm i

reference-implementation-setup-nitro-prepare:
	cd apps/api && npm run prepare

reference-implementation-setup-db-generate:
	cd apps/api/server && npm run db:generate

reference-implementation-setup:
	make reference-implementation-setup-install-dependencies
	echo -e '\n\033[0;32m    INSTALLED DEPENDENCIES\033[0m\n'
	make reference-implementation-setup-nitro-prepare
	echo -e '\n\033[0;32m    PREPARED NITRO\033[0m\n'
	make reference-implementation-setup-db-generate
	echo -e '\n\033[0;32m    GENERATED PRISMA\033[0m\n'

########################
# Reference Implementation - Run

reference-implementation-run-for-postman:  # WARNING clearly not production ready
	JWT_SECRET=dxLmhnE0pRY2+vUlu+i5Pxh8LTxLBTgBWdp82W74mMs= npm -C apps/api run dev

########################
# Reference Implementation - Tests

reference-implementation-test-with-postman-and-already-launched-server:
	DELAY_REQUEST=50 APIURL=http://localhost:3000/api api/run-api-tests.sh

reference-implementation-test-with-postman:
	@set -e; \
	JWT_SECRET=dxLmhnE0pRY2+vUlu+i5Pxh8LTxLBTgBWdp82W74mMs= npm -C apps/api run dev & \
	SERVER_PID=$$!; \
	trap "kill $$SERVER_PID 2>/dev/null || true" EXIT; \
	sleep 0.3; \
	kill -0 "$$SERVER_PID" 2>/dev/null || exit 4; \
	make reference-implementation-test-with-postman-and-already-launched-server && ( \
		make running-processes-clean; echo -e '\n\033[0;32m    TESTS OK\033[0m\n' && exit 0 \
	) || ( \
		make running-processes-clean; echo -e '\n\033[0;31m    TESTS FAILED\033[0m\n' && exit 1 \
	)

########################
# Cleaning

running-processes-clean:  # killing the parent is usually not enough, we should kill through this helper
	ps a -A -o pid,cmd \
	| grep "$$(pwd)/apps/api/node_modules/.bin/nitro dev" \
	| cut -d" " -f1 \
	| xargs -I {} kill -9 {} \
	|| true

non-default-files-clean:
	rm -rf apps/api/node_modules  # npm modules - includes some files generated by prisma -> node_modules/@prisma/client
	rm -f appd/api/prisma/dev.db  # dev database

########################
# Documentation

documentation-setup:
	cd apps/documentation && bun install

documentation-dev:
	cd apps/documentation && bun run dev

documentation-dev-host:
	cd apps/documentation && bun run dev --host

documentation-build:
	cd apps/documentation && bun run build

documentation-preview:
	cd apps/documentation && bun run preview

documentation-clean:
	rm -rf apps/documentation/.astro apps/documentation/dist apps/documentation/node_modules
